services:
  web-crawler:
    image: oloco/web_crawler_and_docker:v4.3
    container_name: web-crawler
    restart: unless-stopped
    ports:
      - "80:80"     # Nginx → http://docker.web.casa.lan
      - "3000:3000" # Node.js → http://crawler.web.casa.lan:3000 o proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
networks:
  default:
    driver: bridge
