services:
  # === TU APP ACTUAL (sin cambios en puertos externos) ===
  web:
    build: .
    container_name: crawler-web
    restart: unless-stopped
    expose:
      - "80"        # Solo expone internamente
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy-network

  # === NGINX PROXY CON SSL AUTOMÁTICO ===
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network
    restart: unless-stopped

  # === CERTBOT AUTOMÁTICO (ACME COMPANION) ===
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=${EMAIL}
    networks:
      - proxy-network
    restart: unless-stopped

# === VOLUMENES COMPARTIDOS ===
volumes:
  certs:
  vhost:
  html:
  acme:

# === RED INTERNA ===
networks:
  proxy-network:
    driver: bridge